---
title: 前端错误捕获
order: 1

group:
  title: 页面异常捕获
  order: 5
---

## 为什么捕获错误

在前端项目中，总会遇到各种错误问题需要我们修改，但是每次定位问题的时候总是比较麻烦。尤其 js 是一个弱类型语言，加上浏览器环境、网络问题、书写错误等等各种问题，我们不能每次都是人工去检测，所以就需要在实际生产项目中对错误进行一个监控，以便我们及时发现问题并且优化代码。

这里就先从错误 **（Error）** 开始了解吧：

## Error 的属性和方法

在 ECMAScript 标准中，error 有两个标准属性：

- **Error.prototype.name**: 错误的名字
- **Error.prototype.message**: 错误的描述
  例如，在浏览器输入如下代码：

```js
var a = new Error('111');
console.log(a);
/** 
Error: 111
  at <anonymous>:1:9
*/
console.log(a.name); // Error
console.log(a.message); // 111
```

其次，error 有一个标准方法：

- Error.prototype.toString: 返回一个表示错误的字符串
  例如，在浏览器输入：

```js
var a = new Error('111');
console.log(a.toString()); // Error: 111
```

除了标准属性之外，还有些非标准的属性：

- **Error.prototype.fileName**：产生错误的文件名。
- **Error.prototype.lineNumber**：产生错误的行号。
- **Error.prototype.columnNumber**：产生错误的列号。
- **Error.prototype.stack**：堆栈信息。这个比较常用。
  这些属性在生产环境**谨慎使用**，不过现代浏览器也基本都支持。

## 错误的种类

### js 提供的错误构造函数

除了通用的 Error 构造函数之外，js 还提供了一些其他类型的错误构造函数:
|错误类型|描述|
|:----:|----|
|**InternalError**|**创建一个代表 Javascript 引擎内部错误的异常抛出的实例。** 如: "递归太多"。非 ECMAScript 标准。|
|**RangeError**|**数值变量或参数超出其有效范围。** 如：var a = new Array(-1);|
|**EvalError**|**与 eval()相关的错误。** eval()本身没有正确执行。|
|**ReferenceError**|**引用错误。** 如：console.log(b);|
|**SyntaxError**|**语法错误。** 如：var a = ;|
|**TypeError**|**变量或参数不属于有效范围。** 如：[1,2].split('.')|
|**URIError**|**给 encodeURI 或 decodeURl()传递的参数无效。** 如：decodeURI('%2')|

当 JavaScript 运行过程中出错时，会抛出上 8 种(上述 7 种加上通用错误类型)错误中的其中一种错误。错误类型可以通过 error.name 拿到。

### dom 错误操作

上述错误构造函数是 js 提供的，页面上还会有一些其他的错误，比如错误的操作了 Dom，就会涉及到另外一个对象：**DOMException**。

DOMException 是 W3C DOM 核心对象，表示调用一个 Web Api 时发生的异常。

Web Api 最常见的就是操作 dom 一些方法，还有 XMLHttpRequest、Fetch 等等。

首先来看一个例子：

```js
let error = null;
try {
  const dom1 = document.querySelector('#div');
  const dom2 = dom1.nextSibling;
  const dom3 = document.createElement('div');
  dom1.insertBefore(dom3, dom2);
} catch (e) {
  error = new DOMException(e);
}

/**
  Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at <anonymous>:1:6
*/
```

DOMException 有以下三个属性：

- **DOMException.code** ：错误编号。
- **DOMException.message** ：错误描述。
- **DOMException.name** ：错误名称。
  继续以上面的代码为基础，打印 error，就会得到：

```js
console.log(error);
/**
DOMException: NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
*/
console.log(error.name); // Error
console.log(error.code); // 0
console.log(error.message); // NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

### Promise 的异常

在 Promise 中，如果 Promise 被 reject 了，就会抛出异常：**PromiseRejectionEvent** 。注意，下面两种情况都会导致 Promise 被 reject：

1. 业务代码本身调用了 Promise.reject。
2. Promise 中的代码出错。
   PromiseRejectionEvent 的属性有两个：
3. PromiseRejectionEvent.promise：被 reject 的 Promise。
4. PromiseRejectionEvent.reason：Promise 被 reject 的原因。会传递给 reject。Promsie 的 catch 中的参数。

### 加载资源出错

由于网络，安全等原因，网页加载资源失败，请求接口出错等，也是一种常见的错误。

## 小结

综上所述，一个网页在运行过程中，可能发生四种错误：

1. JavaScript 在运行过程，语言自身抛出的异常。
2. JavaScript 在运行过程中，调用 Web Api 时发生异常。
3. Promise 中的拒绝。
4. 网页加载资源，调用接口时发生异常。
   其中前两种错误可以归为一种：代码写错了。

接下来开始搞错误捕获方式。
